pod:
  ## The annotations of the Ingress Controller pod.
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "10254"
    prometheus.io/scheme: "http"