# role web-dev
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev
subjects:
- kind: Group
  namespace: web
  name: 9fc2a936-d6fe-49e2-969c-5a39edb1d16b