apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-{{ .Chart.Name }}-csi
spec:
  provider: azure
  secretObjects:
  - data:
    - key: sqlpassword
      objectName: sqlpassword
    secretName: keyvault
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ad391820-a9b6-413a-868c-4d9c3fa1b906
    keyvaultName: csas-oh-kv
    cloudName: AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: sqlpassword
          objectType: secret
          objectVersion: ""
    tenantId: d1334b46-4116-4319-9a32-7d394171a9be
