apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-{{ .Chart.Name }}-csi
spec:
  provider: azure
  secretObjects:
  - data:
    {{- with .Values.env.secrets }}
    {{- range $k, $v := . }}
    - key: {{ quote $v }}
      objectName: {{ quote $v }}
    {{- end }}
    {{- end }}
    secretName: keyvault
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 7e931fdb-b623-43b2-8141-ec448f07dea1
    keyvaultName: csas-oh-kv
    cloudName: AzurePublicCloud
    objects:  |
      array:
      {{- with .Values.env.secrets }}
      {{- range $k, $v := . }}
        - |
          objectName: {{ quote $v }}
          objectType: secret
          objectVersion: ""
      {{- end }}
      {{- end }}
    tenantId: d1334b46-4116-4319-9a32-7d394171a9be
